import re
import unittest
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parent.parent


class FrontendCacheSettingsContractTests(unittest.TestCase):
    def test_cache_select_exposes_no_limit_option(self):
        html = (ROOT_DIR / "web" / "index.html").read_text(encoding="utf-8")

        self.assertIn('id="geotiff-cache-limit"', html)
        self.assertIn('value="none"', html)
        self.assertIn('data-i18n="modal.settings.cacheNone"', html)

    def test_no_limit_option_round_trips_as_null_in_frontend_logic(self):
        app_js = (ROOT_DIR / "web" / "app.js").read_text(encoding="utf-8")

        self.assertIn("geotiffCacheControl?.value === 'none'", app_js)
        self.assertIn("return { max_gb: null }", app_js)
        self.assertIn("settings.max_gb === null", app_js)
        self.assertIn("geotiffCacheControl.value = 'none'", app_js)

    def test_no_limit_option_has_translations(self):
        i18n_js = (ROOT_DIR / "web" / "i18n.js").read_text(encoding="utf-8")

        self.assertIn("'modal.settings.cacheNone': 'Bez limitu'", i18n_js)
        self.assertIn("'modal.settings.cacheNone': 'No limit'", i18n_js)

    def test_frontend_uses_relative_backend_urls_for_tunnel_deployments(self):
        html = (ROOT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        app_js = (ROOT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        config_js = (ROOT_DIR / "web" / "config.js").read_text(encoding="utf-8")
        styles = (ROOT_DIR / "web" / "styles.css").read_text(encoding="utf-8")

        self.assertNotIn("http://${window.location.hostname}:8000", app_js)
        self.assertIn('<script src="/config.js"></script>', html)
        self.assertIn('<script src="/ui.js"></script>', html)
        self.assertIn('<script src="/admin.js"></script>', html)
        self.assertIn('<script src="/map_helpers.js"></script>', html)
        self.assertLess(html.index('<script src="/config.js"></script>'), html.index('<script src="/app.js"></script>'))
        self.assertLess(html.index('<script src="/ui.js"></script>'), html.index('<script src="/app.js"></script>'))
        self.assertLess(html.index('<script src="/admin.js"></script>'), html.index('<script src="/app.js"></script>'))
        self.assertLess(
            html.index('<script src="/map_helpers.js"></script>'), html.index('<script src="/app.js"></script>')
        )
        self.assertIn("const API_URL = '/api/download'", config_js)
        self.assertIn("L.tileLayer.wms(`/wms_proxy/", app_js)
        self.assertIn("function buildMapSourceLayer(source)", app_js)
        self.assertIn("function setMapSource(index)", app_js)
        self.assertIn("function setMapSourceByVisiblePosition(position)", app_js)
        self.assertIn("function moveMapSource(delta)", app_js)
        self.assertIn("function renderMapSourceTicks(visibleIndices = visibleMapSourceIndices())", app_js)
        self.assertIn("function updateMapSourceAvailability()", app_js)
        self.assertIn("let currentMapSourceIndex", app_js)
        self.assertIn("visibleIndices.forEach(index =>", app_js)
        self.assertIn("tick.dataset.index = index", app_js)
        self.assertIn("tick.textContent = source.shortLabel", app_js)
        self.assertIn("tick.title = source.label", app_js)
        self.assertIn("range.max = Math.max(0, visibleIndices.length - 1)", app_js)
        self.assertIn("source.type === 'tile'", app_js)
        self.assertIn("function buildMapLabelLayer()", app_js)
        self.assertIn("activeMapSource().labelsOverlay !== false", app_js)
        self.assertIn("const OSM_TILE_URL = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'", config_js)
        self.assertIn(
            "const CARTO_LABELS_TILE_URL = 'https://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}{r}.png'",
            config_js,
        )
        self.assertIn("shortLabel: 'OSM'", config_js)
        self.assertIn("publicLayerKey: PUBLIC_LAYER_KEYS.baseMapOsm", config_js)
        self.assertIn("const currentLabel = document.getElementById('year-current')", app_js)
        self.assertIn("currentLabel.textContent = source.shortLabel", app_js)
        self.assertIn("currentLabel.title = source.label", app_js)
        self.assertIn("grid-template-areas:\n            \"prev track next\"\n            \". current .\";", styles)
        self.assertIn("width: min(420px, calc(100vw - 24px));", styles)
        self.assertIn("let mapSourceSwapToken = 0", app_js)
        self.assertIn("const swapToken = ++mapSourceSwapToken", app_js)
        self.assertNotIn("function setYear(", app_js)
        self.assertNotIn("let currentYear", app_js)
        self.assertNotIn("ORTHO_YEARS", app_js)

        set_source_slice = app_js[
            app_js.index("function setMapSource(index)") : app_js.index("mapSourceLayer = buildMapSourceLayer")
        ]
        self.assertNotIn("setView", set_source_slice)
        self.assertNotIn("fitBounds", set_source_slice)
        self.assertNotIn("panTo", set_source_slice)

    def test_report_package_modal_and_admin_popup_action_exist(self):
        html = (ROOT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        app_js = (ROOT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        config_js = (ROOT_DIR / "web" / "config.js").read_text(encoding="utf-8")
        ui_js = (ROOT_DIR / "web" / "ui.js").read_text(encoding="utf-8")
        i18n_js = (ROOT_DIR / "web" / "i18n.js").read_text(encoding="utf-8")
        styles = (ROOT_DIR / "web" / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="modal-report-package"', html)
        self.assertIn('id="report-package-pdf"', html)
        self.assertIn('data-i18n="modal.report.downloadPdf"', html)
        self.assertIn('id="report-package-extra-photos"', html)
        self.assertIn('id="modal-wreck-photo-upload"', html)
        self.assertIn('id="wreck-photo-files"', html)
        self.assertIn('class="file-picker-input" id="wreck-photo-files"', html)
        self.assertIn('data-i18n="modal.wreckPhoto.chooseFiles"', html)
        self.assertIn('data-file-summary-for="wreck-photo-files"', html)
        self.assertIn('class="file-picker-input" id="report-photos"', html)
        self.assertIn('data-i18n="modal.report.choosePhotos"', html)
        self.assertIn('data-file-summary-for="report-photos"', html)
        self.assertIn('name="photos[]"', html)
        self.assertIn('id="open-photo-review"', html)
        self.assertIn('id="modal-photo-review"', html)
        self.assertIn('id="open-wreck-review"', html)
        self.assertIn('id="modal-wreck-review"', html)
        self.assertIn('id="open-privacy-requests"', html)
        self.assertIn('id="modal-privacy-requests"', html)
        self.assertIn('id="open-geotiff-cache"', html)
        self.assertIn('id="modal-geotiff-cache"', html)
        self.assertIn('id="geotiff-cache-list"', html)
        self.assertIn('id="open-admin-panel"', html)
        self.assertIn('id="modal-admin-panel"', html)
        self.assertIn('class="modal-backdrop modal-backdrop--floating" id="modal-admin-panel"', html)
        self.assertIn('class="modal modal--admin-panel draggable-modal"', html)
        self.assertIn('class="modal-header modal-drag-handle"', html)
        self.assertIn('id="photo-retention-section"', html)
        self.assertIn('class="modal-section admin-panel-section admin-panel-section--retention"', html)
        self.assertIn('class="setting-actions retention-actions"', html)
        self.assertIn('id="photo-retention-status"', html)
        self.assertIn('id="admin-layer-saved-wrecks"', html)
        self.assertIn('id="admin-layer-cadastral"', html)
        self.assertIn('id="admin-layer-surface"', html)
        self.assertIn('id="admin-layer-base-map-osm"', html)
        self.assertIn('id="admin-public-layers-save"', html)
        self.assertIn('id="admin-feature-scan-analysis"', html)
        self.assertIn('id="admin-feature-yolo-wrecks"', html)
        self.assertIn('id="admin-feature-manual-wrecks"', html)
        self.assertIn('id="admin-feature-photo-uploads"', html)
        self.assertIn('id="admin-public-features-save"', html)
        self.assertIn('id="context-add-field-photos"', html)
        self.assertIn('data-i18n="modal.adminPanel.publicLayers"', html)
        self.assertIn('data-i18n="modal.adminPanel.publicFeatures"', html)
        self.assertIn("const MODAL_POSITION_STORAGE_PREFIX", config_js)
        self.assertIn("`${MODAL_POSITION_STORAGE_PREFIX}${backdrop.id}`", ui_js)
        self.assertIn("function hideModalBackdrop(backdrop)", ui_js)
        self.assertIn("new CustomEvent('modalclose'", ui_js)
        self.assertIn(".modal--geotiff-cache {\n    width: min(680px, calc(100vw - 24px));", styles)
        self.assertIn("pointer-events: auto;\n}", styles[styles.index(".modal--geotiff-cache {") :])
        self.assertIn('id="privacy-request-filter"', html)
        self.assertIn('id="privacy-request-admin-note"', app_js)
        self.assertIn('href="/privacy"', html)
        self.assertIn('href="/report"', html)
        self.assertIn('id="modal-admin-login"', html)
        self.assertIn('id="panel-title" data-i18n="panel.title">Wrocław', html)
        self.assertIn('id="lingering-cars-badge"', html)
        self.assertIn('class="panel-title-wrap"', html)
        self.assertNotIn('id="lingering-cars-counter"', html)
        self.assertNotIn('data-i18n="panel.lingeringCars"', html)
        self.assertNotIn('class="sep lingering-cars-sep"', html)
        self.assertNotIn("panel-scan-trigger", html)
        self.assertNotIn("panel-title-stack", html)
        self.assertNotIn('data-i18n-attr="title:panel.scanTitle"', html)
        self.assertIn("openReportPackageModal('${wreckId}')", app_js)
        self.assertIn("openWreckPhotoModal('${wreckId}')", app_js)
        self.assertIn("function popupPhotoGrid(previews", app_js)
        self.assertIn("function popupPhotoSection(title, previews", app_js)
        self.assertIn("wreck.field_photo_previews", app_js)
        self.assertIn("wreck.evidence_previews", app_js)
        self.assertNotIn("wreck.preview_photos", app_js)
        self.assertNotIn("wreck-popup-preview-download", app_js)
        self.assertNotIn("function linkedFieldPhotoCountForWreck", app_js)
        self.assertNotIn("function wreckBadgePhotoCount", app_js)
        self.assertIn("icon: wreckIcon(wreck.photo_count, wreck.public_review_status)", app_js)
        self.assertIn("const photoButton = publicFeatureAllowed(PUBLIC_FEATURE_KEYS.photoUploads)", app_js)
        self.assertNotIn("const photoButton = adminAuthenticated", app_js)
        self.assertIn("const reviewPhotoCount = Number(wreck.review_photo_count || 0)", app_js)
        self.assertIn("const reviewPhotosButton = adminAuthenticated && reviewPhotoCount > 0", app_js)
        self.assertIn("openPhotoReviewForWreck('${wreckId}')", app_js)
        self.assertIn("function reviewWreckStatus(wreckId, publicReviewStatus, button = null)", app_js)
        self.assertIn("function openWreckReviewModal()", app_js)
        self.assertIn("function loadWreckReviewQueue()", app_js)
        self.assertIn("function saveWreckReviewStatus(publicReviewStatus)", app_js)
        self.assertIn("function deleteWreckReviewItem()", app_js)
        self.assertIn("function focusWreckReviewOnMap()", app_js)
        self.assertIn("popupCompactLink(folder, t('wreck.openCaseShort')", app_js)
        self.assertIn("popupCompactLink(links.street_view, 'SV'", app_js)
        self.assertIn("popupCompactLink(links.google_maps_satellite, 'Sat'", app_js)
        self.assertIn('class="map-popup-actions"', app_js)
        self.assertIn("t('wreck.popup.fieldPhotos')", app_js)
        self.assertIn("t('wreck.popup.evidencePreviews')", app_js)
        self.assertIn("report-package", app_js)
        self.assertIn("async function openReportPackageModal(wreckId, options = {}) {", app_js)
        self.assertNotIn(
            "async function openReportPackageModal(wreckId, options = {}) {\n    if (!(await ensureAdmin())) return;",
            app_js,
        )
        self.assertIn("const reportPath = adminAuthenticated ? 'report-package' : 'public-report-package';", app_js)
        self.assertIn("document.getElementById('report-package-pdf').href = data.pdf_url || '#'", app_js)
        self.assertIn("rotatePhotoRedaction(5)", html)
        self.assertIn('class="review-tool-actions"', html)
        self.assertIn('class="review-decision-actions"', html)
        self.assertIn('class="report-copy-btn review-icon-btn"', html)
        self.assertIn("data-i18n-attr=\"title:modal.photoReview.undo;aria-label:modal.photoReview.undo\"", html)
        self.assertIn("data-i18n-attr=\"title:modal.wreckReview.showOnMap;aria-label:modal.wreckReview.showOnMap\"", html)
        self.assertIn('data-i18n="modal.photoReview.savePendingShort"', html)
        self.assertIn('data-i18n="modal.photoReview.deleteShort"', html)
        self.assertIn('data-i18n="modal.wreckReview.savePendingShort"', html)
        self.assertIn('data-i18n="modal.wreckReview.deleteShort"', html)
        self.assertIn('class="review-action-icon"', html)
        self.assertIn('class="review-action-label"', html)
        self.assertIn("data-i18n-attr=\"title:modal.photoReview.approve;aria-label:modal.photoReview.approve\"", html)
        self.assertIn("data-i18n-attr=\"title:modal.wreckReview.approve;aria-label:modal.wreckReview.approve\"", html)
        self.assertIn('id="photo-review-delete"', html)
        self.assertIn("onclick=\"deletePhotoReviewItem()\"", html)
        self.assertIn("function rotatePhotoRedaction(degrees)", app_js)
        self.assertIn("function moveRedaction(redaction, dx, dy)", app_js)
        self.assertIn(
            "function redactionHandleAtPoint(point, redactionIndex = activePhotoReviewRedactionIndex)", app_js
        )
        self.assertIn("function resizeRedactionPoint(redaction, pointIndex, point)", app_js)
        self.assertIn("function photoReviewCanvasMetrics", app_js)
        self.assertIn("PHOTO_REVIEW_HANDLE_HIT_RADIUS_PX = 18", app_js)
        self.assertIn("const updateHoverState = event =>", app_js)
        self.assertIn("canvas.addEventListener('pointerdown'", app_js)
        self.assertIn("canvas.addEventListener('pointermove'", app_js)
        self.assertIn("function capturePhotoReviewPointer(canvas, pointerId)", app_js)
        self.assertIn("canvas.setPointerCapture?.(pointerId)", app_js)
        self.assertIn("function releasePhotoReviewPointer(canvas, pointerId)", app_js)
        self.assertNotIn("canvas.addEventListener('mousedown'", app_js)
        self.assertIn("canvas.classList.add('is-moving-redaction')", app_js)
        self.assertIn("canvas.classList.add('is-resizing-redaction')", app_js)
        self.assertIn("canvas.classList.add('is-hovering-handle')", app_js)
        self.assertIn("canvas.classList.add('is-hovering-redaction')", app_js)
        self.assertIn("#photo-review-canvas.is-moving-redaction", styles)
        self.assertIn("#photo-review-canvas.is-resizing-redaction", styles)
        self.assertIn("#photo-review-canvas.is-hovering-handle", styles)
        self.assertIn("#photo-review-canvas.is-hovering-redaction", styles)
        self.assertIn("touch-action: none", styles)
        self.assertIn(".review-icon-btn", styles)
        self.assertIn(".review-action-icon", styles)
        self.assertIn(".review-action-label", styles)
        self.assertIn(".review-decision-actions", styles)
        self.assertIn(".review-approve-btn", styles)
        self.assertIn("@media (max-width: 520px)", styles)
        self.assertIn("flex: 0 0 40px", styles)
        self.assertIn("normalizePhotoReviewRedaction", app_js)
        self.assertIn("function submitWreckPhotoUpload(event)", app_js)
        self.assertIn("function validateWreckPhotoFiles(files)", app_js)
        self.assertIn("function openPhotoReviewModal()", app_js)
        self.assertIn("function savePhotoReviewStatus(publicReviewStatus)", app_js)
        self.assertIn("function photoReviewDeleteEndpoint(item)", app_js)
        self.assertIn("function deletePhotoReviewItem()", app_js)
        self.assertIn("activePhotoReview?.public_review_status === 'rejected'", app_js)
        self.assertIn("method: 'DELETE'", app_js)
        self.assertIn("public_review_status: publicReviewStatus", app_js)
        self.assertIn("WRECK_PHOTO_MAX_COUNT = 25", config_js)
        self.assertIn("WRECK_PHOTO_MAX_BYTES = 10 * 1024 * 1024", config_js)
        self.assertIn("const ADMIN_PHOTOS_URL = '/api/admin/photos'", config_js)
        self.assertIn("const ADMIN_PRIVACY_REQUESTS_URL = '/api/admin/privacy-requests'", config_js)
        self.assertIn("const ADMIN_PHOTO_RETENTION_URL = '/api/admin/photo-retention'", config_js)
        self.assertIn("const ADMIN_WRECKS_URL = '/api/admin/wrecks'", config_js)
        self.assertIn("'modal.photoReview.delete': 'Usuń zdjęcie'", i18n_js)
        self.assertIn("'modal.photoReview.delete': 'Delete photo'", i18n_js)
        self.assertIn("'modal.photoReview.savePendingShort': 'Do weryfikacji'", i18n_js)
        self.assertIn("'modal.photoReview.savePendingShort': 'Needs review'", i18n_js)
        self.assertIn("'modal.photoReview.deleteShort': 'Usuń'", i18n_js)
        self.assertIn("'modal.photoReview.deleteShort': 'Delete'", i18n_js)
        self.assertIn("'modal.photoReview.approve': 'Zatwierdź'", i18n_js)
        self.assertIn("'modal.photoReview.approve': 'Approve'", i18n_js)
        self.assertIn("'modal.wreckReview.title': 'Przegląd spraw pojazdów'", i18n_js)
        self.assertIn("'modal.wreckReview.title': 'Vehicle case review'", i18n_js)
        self.assertIn("'modal.wreckReview.savePendingShort': 'Do weryfikacji'", i18n_js)
        self.assertIn("'modal.wreckReview.savePendingShort': 'Needs review'", i18n_js)
        self.assertIn("'modal.wreckReview.deleteShort': 'Usuń'", i18n_js)
        self.assertIn("'modal.wreckReview.deleteShort': 'Delete'", i18n_js)
        self.assertIn("'modal.wreckReview.approve': 'Zatwierdź'", i18n_js)
        self.assertIn("'modal.wreckReview.approve': 'Approve'", i18n_js)
        self.assertIn("const ADMIN_GEOTIFF_CACHE_URL = '/api/admin/geotiff-cache'", config_js)
        self.assertIn("function openGeotiffCacheModal()", app_js)
        self.assertIn("function renderGeotiffCacheStatus(data = {})", app_js)
        self.assertIn("function clearGeotiffCacheLayer(options = {})", app_js)
        self.assertIn("function renderGeotiffCacheLayer(data = {})", app_js)
        self.assertIn("function selectGeotiffCacheItem(fileName, options = {})", app_js)
        self.assertIn("async function deleteGeotiffCacheItem(fileName, button = null)", app_js)
        self.assertIn("geotiffCacheRectanglesByFile.set(file, rect)", app_js)
        self.assertIn("geotiffCacheRectangleStyle(file === selectedGeotiffCacheFile)", app_js)
        self.assertIn("deleteGeotiffCacheItem(deleteButton.dataset.file, deleteButton)", app_js)
        self.assertIn('class="geotiff-cache-delete"', app_js)
        self.assertIn("`${ADMIN_GEOTIFF_CACHE_URL}/${encodeURIComponent(file)}`", app_js)
        self.assertIn("geotiffCacheLayer = L.layerGroup(rectangles).addTo(map)", app_js)
        self.assertIn(
            "document.getElementById('modal-geotiff-cache')?.addEventListener('modalclose', clearGeotiffCacheLayer)",
            app_js,
        )
        self.assertIn("function openPrivacyRequestsModal()", app_js)
        self.assertIn("async function loadPrivacyRequestQueue()", app_js)
        self.assertIn("async function savePrivacyRequestUpdate()", app_js)
        self.assertIn("async function loadPhotoRetentionStatus()", app_js)
        self.assertIn("async function runPhotoRetention(dryRun = true)", app_js)
        self.assertIn("'modal.settings.photoRetention': 'Retencja oryginałów'", i18n_js)
        self.assertIn("method: 'PATCH'", app_js)
        self.assertIn("'modal.privacyRequests.title': 'Zgłoszenia prywatności'", i18n_js)
        self.assertIn("'icon.privacyRequests': 'Zgłoszenia prywatności'", i18n_js)
        self.assertIn(".privacy-request-layout", styles)
        self.assertIn("`${WRECKS_URL}/${encodeURIComponent(wreckId)}/photos`", app_js)
        self.assertIn("REPORT_PHOTO_MAX_COUNT = 5", config_js)
        self.assertIn("REPORT_PHOTO_MAX_BYTES = 10 * 1024 * 1024", config_js)
        self.assertIn("const saveButton = yoloWrecksAllowed", app_js)
        self.assertNotIn("const saveButton = adminAuthenticated", app_js)
        self.assertNotIn("window.prompt", app_js)
        self.assertIn("'wreck.reportPackage': 'Generuj zgłoszenie do weryfikacji'", i18n_js)
        self.assertIn("'panel.lingeringCarsTooltip': 'Pojazdy udokumentowane zdjęciami w terenie'", i18n_js)
        self.assertNotIn("'panel.lingeringCars'", i18n_js)
        self.assertNotIn("'panel.scanTitle'", i18n_js)
        self.assertIn("'wreck.addPhotos': 'Dodaj zdjęcia'", i18n_js)
        self.assertIn("'modal.wreckPhoto.title': 'Zdjęcia do sprawy pojazdu'", i18n_js)
        self.assertIn("'modal.wreckPhoto.chooseFiles': 'Wybierz zdjęcia do sprawy'", i18n_js)
        self.assertIn("'modal.wreckPhoto.submit': 'Dodaj do sprawy'", i18n_js)
        self.assertIn("'modal.report.choosePhotos': 'Wybierz załączniki do zgłoszenia'", i18n_js)
        self.assertIn("'filePicker.empty': 'Nie wybrano plików'", i18n_js)
        self.assertIn("'filePicker.selectedMany': '{n} files selected'", i18n_js)
        self.assertIn("'modal.photoReview.title': 'Przegląd zdjęć'", i18n_js)
        self.assertIn("'modal.photoReview.search': 'Szukaj id / sprawy'", i18n_js)
        self.assertIn("'wreck.popup.title': 'Sprawa pojazdu'", i18n_js)
        self.assertIn("'wreck.popup.title': 'Vehicle case'", i18n_js)
        self.assertIn("'modal.geotiffCache.title': 'Cache GeoTIFF'", i18n_js)
        self.assertIn("'modal.geotiffCache.delete': 'Usuń kafel'", i18n_js)
        self.assertIn("'modal.geotiffCache.delete': 'Delete tile'", i18n_js)
        self.assertIn("'icon.geotiffCache': 'Cache GeoTIFF'", i18n_js)
        self.assertIn(".geotiff-cache-item.is-selected", styles)
        self.assertIn(".geotiff-cache-delete", styles)
        self.assertIn("'wreck.reviewPhotos': 'Edytuj anonimizację'", i18n_js)
        self.assertIn("'wreck.approve': 'Zatwierdź sprawę'", i18n_js)
        self.assertIn("'footer.privacy': 'Prywatność'", i18n_js)
        self.assertIn("'footer.report': 'Zgłoś problem'", i18n_js)
        self.assertIn("'modal.wreckPhoto.fileCountError': 'Choose up to {n} photos at a time.'", i18n_js)
        self.assertIn("'modal.report.submit': 'Generate report'", i18n_js)
        self.assertIn("'modal.report.downloadPdf': 'Download PDF'", i18n_js)
        self.assertIn("'modal.report.title': 'Zgłoszenie do weryfikacji'", i18n_js)
        self.assertIn("'modal.report.title': 'Verification report'", i18n_js)
        self.assertIn("title.textContent = t('panel.title')", ui_js)
        self.assertIn('id="panel-header-toggle"', html)
        self.assertIn('onclick="togglePanel()"', html)
        self.assertIn('onkeydown="handlePanelHeaderToggleKey(event)"', html)
        self.assertIn("function handlePanelHeaderToggleKey(event)", ui_js)
        self.assertIn(".panel-header-toggle", styles)
        self.assertNotIn('id="toggle-panel"', html)
        self.assertNotIn("panel.scanCollapsed", app_js)
        self.assertNotIn("panel.scanCollapsed", ui_js)
        self.assertIn("'panel.title': 'Wrocław'", i18n_js)
        self.assertNotIn("'panel.scanCollapsed'", i18n_js)
        self.assertIn("'modal.admin.title': 'Panel administratora'", i18n_js)
        self.assertIn(".panel-title-wrap", styles)
        self.assertIn(".lingering-cars-badge", styles)
        self.assertNotIn(".lingering-cars-counter", styles)
        self.assertNotIn("hr.lingering-cars-sep", styles)
        self.assertNotIn(".panel-scan-trigger", styles)
        self.assertNotIn(".panel-title-stack", styles)

    def test_language_control_lives_inside_compact_settings_modal_without_duplicate_help(self):
        html = (ROOT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        app_js = (ROOT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        ui_js = (ROOT_DIR / "web" / "ui.js").read_text(encoding="utf-8")
        styles = (ROOT_DIR / "web" / "styles.css").read_text(encoding="utf-8")

        self.assertNotIn('id="toggle-lang"', html)
        self.assertIn('id="open-help"', html)
        self.assertIn('class="btn-icon" id="open-settings"', html)
        self.assertIn('class="btn-icon" id="open-admin-panel"', html)
        self.assertNotIn('class="btn-icon admin-only" id="open-settings"', html)
        self.assertIn('id="settings-toggle-lang"', html)
        self.assertIn('id="settings-lang-label"', html)
        self.assertNotIn('id="settings-open-help"', html)
        self.assertIn("document.querySelectorAll('.lang-label')", ui_js)
        self.assertNotIn("document.querySelectorAll('.lang-label')", app_js)
        self.assertIn("width: min(430px, calc(100vw - 24px))", styles)
        self.assertIn(".modal--settings .modal-body", styles)
        self.assertIn("gap: 10px", styles)
        self.assertNotIn(".lang-switch", styles)
        self.assertNotIn(".draggable-modal.is-dragging {\n    animation: none;", styles)

    def test_all_modals_are_draggable_and_selects_show_dropdown_indicator(self):
        html = (ROOT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        styles = (ROOT_DIR / "web" / "styles.css").read_text(encoding="utf-8")
        ui_js = (ROOT_DIR / "web" / "ui.js").read_text(encoding="utf-8")

        modal_dialogs = re.findall(r'class="modal(?:\s|")', html)
        draggable_dialogs = re.findall(r'class="modal[^"]*\bdraggable-modal\b', html)
        drag_handles = re.findall(r'class="modal-header[^"]*\bmodal-drag-handle\b', html)
        self.assertEqual(len(modal_dialogs), len(draggable_dialogs))
        self.assertEqual(len(modal_dialogs), len(drag_handles))
        self.assertIn("document.querySelectorAll('.draggable-modal .modal-drag-handle')", ui_js)
        self.assertIn("dialog.style.position = 'fixed'", ui_js)
        self.assertIn("function resetModalPosition(dialog)", ui_js)
        self.assertIn("function centerModalPosition(dialog)", ui_js)
        self.assertIn("function shouldCenterDraggableModals()", ui_js)
        self.assertIn("window.matchMedia('(max-width: 640px), (max-height: 520px)')", ui_js)
        self.assertIn("if (shouldCenterDraggableModals()) {\n        resetModalPosition(dialog);", ui_js)
        self.assertIn("if (shouldCenterDraggableModals()) return;", ui_js)
        self.assertIn(".modal-backdrop:not(.modal-backdrop--floating)", styles)
        self.assertIn(".modal-backdrop:not(.modal-backdrop--floating) .modal", styles)
        self.assertIn("max-height: calc(100dvh - 24px)", styles)
        self.assertIn(".modal--photo-review,\n    .modal--wreck-review,\n    .modal--privacy-requests", styles)
        self.assertIn("min-width: 0", styles)
        self.assertIn("requestAnimationFrame(() => centerModalPosition(dialog))", ui_js)
        self.assertIn("--select-chevron", styles)
        self.assertIn("select.modal-input", styles)
        self.assertIn("background-image: var(--select-chevron)", styles)

    def test_settings_modal_is_visible_with_locked_admin_controls_for_guests(self):
        html = (ROOT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        app_js = (ROOT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        admin_js = (ROOT_DIR / "web" / "admin.js").read_text(encoding="utf-8")
        i18n_js = (ROOT_DIR / "web" / "i18n.js").read_text(encoding="utf-8")
        styles = (ROOT_DIR / "web" / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="settings-lock-hint"', html)
        self.assertIn("function updateSettingsAccess()", app_js)
        self.assertIn("const adminSettingsControls = [", app_js)
        self.assertIn("settingsModal?.classList.toggle('settings-locked', locked)", app_js)
        self.assertIn("control.disabled = locked", app_js)
        self.assertIn("async function openSettingsModal()", admin_js)
        self.assertIn("async function openAdminPanel()", admin_js)
        self.assertNotIn("async function openSettingsModal()", app_js)
        self.assertNotIn("if (!(await ensureAdmin())) return;\n    openModal('modal-settings')", app_js)
        self.assertIn("'modal.settings.lockedHint': 'Log in as administrator to edit settings.'", i18n_js)
        self.assertIn(".settings-lock-hint", styles)
        self.assertIn(".modal--settings select:disabled", styles)

    def test_privacy_and_report_pages_have_english_i18n_coverage(self):
        index_html = (ROOT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        privacy_html = (ROOT_DIR / "web" / "privacy.html").read_text(encoding="utf-8")
        report_html = (ROOT_DIR / "web" / "report.html").read_text(encoding="utf-8")
        i18n_js = (ROOT_DIR / "web" / "i18n.js").read_text(encoding="utf-8")

        self.assertIn("<title>Wroclaw</title>", index_html)
        self.assertIn("'meta.title': 'Wroclaw'", i18n_js)
        self.assertNotIn("Wrocław Ortho", index_html + i18n_js)
        self.assertNotIn("Pobierz dane dla AI", index_html + i18n_js)
        self.assertIn('data-i18n-title="page.privacy.title"', privacy_html)
        self.assertIn('data-i18n-description="page.privacy.description"', privacy_html)
        self.assertIn('data-i18n="page.privacy.intro"', privacy_html)
        self.assertIn('data-i18n="page.privacy.adminBody" data-i18n-html', privacy_html)
        self.assertIn('data-i18n="page.privacy.legalBody"', privacy_html)
        self.assertIn('data-i18n="page.privacy.scopeBody"', privacy_html)
        self.assertIn('data-i18n="page.privacy.requestsBody" data-i18n-html', privacy_html)
        self.assertIn('data-i18n="page.privacy.recipientsBody"', privacy_html)
        self.assertIn('data-i18n="page.privacy.rightsBody"', privacy_html)
        self.assertIn('data-i18n="page.privacy.complaintBody"', privacy_html)
        self.assertIn('data-i18n="page.privacy.logsBody"', privacy_html)
        self.assertIn('<script src="/i18n.js"></script>', privacy_html)
        self.assertIn('data-i18n-title="page.report.title"', report_html)
        self.assertIn('data-i18n-description="page.report.description"', report_html)
        self.assertIn('data-i18n="page.report.submit"', report_html)
        self.assertIn("status.textContent = t('page.report.sending')", report_html)
        self.assertIn('<script src="/i18n.js"></script>', report_html)
        self.assertIn("const titleKey = document.documentElement.dataset.i18nTitle || 'meta.title'", i18n_js)
        self.assertIn("'page.privacy.title': 'Privacy - WreckScanner'", i18n_js)
        self.assertIn("'page.privacy.adminTitle': 'Controller and contact'", i18n_js)
        self.assertIn("'page.privacy.complaintTitle': 'Complaint to UODO'", i18n_js)
        self.assertIn("'page.privacy.logsTitle': 'Technical logs'", i18n_js)
        self.assertIn("'page.report.title': 'Report a problem - WreckScanner'", i18n_js)
        self.assertIn("'page.report.saved': 'Request saved: {id}.'", i18n_js)
        self.assertIn("'modal.adminPanel.title': 'Administrator panel'", i18n_js)
        self.assertIn("'modal.adminPanel.publicLayers': 'Layers for signed-out users'", i18n_js)

    def test_readme_documents_photo_privacy_contract(self):
        readme_pl = (ROOT_DIR / "README.md").read_text(encoding="utf-8")
        readme_en = (ROOT_DIR / "docs" / "README.en.md").read_text(encoding="utf-8")

        self.assertIn("Publiczne API zwraca tylko `public_image` i `public_thumb`", readme_pl)
        self.assertIn("Oryginały są dostępne tylko przez endpointy administracyjne.", readme_pl)
        self.assertNotIn("web/photo", readme_pl)
        self.assertNotIn("Warstwa zdjęć terenowych, miniatury i oryginały są publicznie widoczne", readme_pl)
        self.assertIn("The public API returns only `public_image` and `public_thumb`", readme_en)
        self.assertIn("Originals are available only through administrator endpoints.", readme_en)
        self.assertNotIn("web/photo", readme_en)
        self.assertNotIn("The field photo layer, thumbnails, and originals are publicly visible", readme_en)

    def test_admin_login_and_delete_confirmation_use_app_modal_styles(self):
        html = (ROOT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        admin_js = (ROOT_DIR / "web" / "admin.js").read_text(encoding="utf-8")
        ui_js = (ROOT_DIR / "web" / "ui.js").read_text(encoding="utf-8")
        i18n_js = (ROOT_DIR / "web" / "i18n.js").read_text(encoding="utf-8")
        styles = (ROOT_DIR / "web" / "styles.css").read_text(encoding="utf-8")

        self.assertIn('class="modal-input" id="admin-password-input"', html)
        self.assertIn('id="modal-confirm"', html)
        self.assertIn('id="confirm-message"', html)
        self.assertIn("function confirmAction", ui_js)
        self.assertIn("function openModal(id, options = {})", ui_js)
        self.assertIn("openModal('modal-confirm', { preserveOpen: true })", ui_js)
        self.assertIn("closeConfirmModal(false)", ui_js)
        self.assertIn("async function submitAdminLogin(event)", admin_js)
        self.assertNotIn("window.confirm", ui_js)
        self.assertIn(".modal-input", styles)
        self.assertIn("min-height: 42px", styles)
        self.assertIn(".modal-input:-webkit-autofill", styles)
        self.assertIn(".modal--confirm", styles)
        self.assertIn("#modal-confirm", styles)
        self.assertIn("z-index: 1200", styles)
        self.assertIn(".confirm-danger-btn", styles)
        self.assertIn("'modal.confirm.cancel': 'Anuluj'", i18n_js)
        self.assertIn("'fieldPhoto.deleteTitle': 'Delete field photos?'", i18n_js)
        self.assertIn("'wreck.deleteTitle': 'Delete vehicle case?'", i18n_js)

    def test_admin_field_photo_upload_layer_exists(self):
        html = (ROOT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        app_js = (ROOT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        config_js = (ROOT_DIR / "web" / "config.js").read_text(encoding="utf-8")
        i18n_js = (ROOT_DIR / "web" / "i18n.js").read_text(encoding="utf-8")
        styles = (ROOT_DIR / "web" / "styles.css").read_text(encoding="utf-8")

        self.assertIn('class="btn-icon" id="open-settings"', html)
        self.assertIn('id="open-field-photo-upload"', html)
        self.assertIn('class="admin-panel-action admin-only" id="open-field-photo-upload"', html)
        self.assertIn('id="modal-field-photo-upload"', html)
        self.assertIn('id="field-photo-issue-type"', html)
        self.assertIn('value="infrastructure"', html)
        self.assertIn('value="smoke"', html)
        self.assertIn('class="map-layer-controls is-loading-public-layers"', html)
        self.assertIn('id="field-photo-files"', html)
        self.assertIn('class="file-picker-input" id="field-photo-files"', html)
        self.assertIn('data-i18n="modal.fieldPhoto.chooseFiles"', html)
        self.assertIn('data-file-summary-for="field-photo-files"', html)
        self.assertIn('id="field-photo-ignore-exif"', html)
        self.assertIn('data-i18n="modal.fieldPhoto.ignoreExifGps"', html)
        self.assertIn('id="field-photo-queue"', html)
        self.assertIn('id="field-photo-retry"', html)
        self.assertIn("const FIELD_PHOTOS_URL = '/api/field-photos'", config_js)
        self.assertIn("const FIELD_PHOTO_MAX_BYTES = 10 * 1024 * 1024", config_js)
        self.assertIn("const FIELD_PHOTO_MAX_FILES = 25", config_js)
        self.assertIn("const FIELD_PHOTO_ISSUE_TYPE_VEHICLE = 'vehicle'", config_js)
        self.assertIn("const FIELD_PHOTO_ISSUE_TYPES = new Set", config_js)
        self.assertIn("const FIELD_PHOTO_GROUP_RADIUS_M = 1", config_js)
        self.assertNotIn("const FIELD_PHOTO_GROUP_RADIUS_M", app_js)
        self.assertIn("let fieldPhotoUploadItems = []", app_js)
        self.assertIn("let fieldPhotoMarkers = []", app_js)
        self.assertIn("const issueSelect = document.getElementById('field-photo-issue-type')", app_js)
        self.assertIn("if (issueSelect) issueSelect.value = requestedIssueType", app_js)
        self.assertIn("function loadFieldPhotos()", app_js)
        self.assertIn("function deleteFieldPhoto", app_js)
        self.assertIn("function uploadFieldPhotoItems(items)", app_js)
        self.assertIn("function retryFailedFieldPhotoUploads()", app_js)
        self.assertIn("if (!publicFeatureAllowed(PUBLIC_FEATURE_KEYS.photoUploads)) return;", app_js)
        self.assertIn("function updateFilePickerSummary(input)", app_js)
        self.assertIn("document.querySelectorAll('.file-picker-input')", app_js)
        self.assertIn("document.addEventListener('langchange', updateAllFilePickerSummaries)", app_js)
        self.assertIn("validationError: Boolean(error)", app_js)
        self.assertIn("formData.append('ignore_exif_gps', item.ignoreExifGps ? '1' : '0')", app_js)
        self.assertIn("formData.append('issue_type', item.issueType || FIELD_PHOTO_ISSUE_TYPE_VEHICLE)", app_js)
        self.assertIn("item.photo = data.photo || null", app_js)
        self.assertNotIn("lat: data.photo?.lat", app_js)
        self.assertNotIn("kind: 'photo'", app_js)
        self.assertIn("closeModal(document.getElementById('modal-field-photo-upload'))", app_js)
        self.assertIn("item.ignoreExifGps = ignoreExifGps", app_js)
        self.assertIn("item.issueType = issueType", app_js)
        self.assertIn("t('modal.fieldPhoto.queueSubmittedForReview')", app_js)
        self.assertIn("t('modal.fieldPhoto.submittedForReview', { n: summary.saved })", app_js)
        self.assertIn("fieldPhotoUploadItems.filter(item => item.status === 'pending')", app_js)
        self.assertIn("function fieldPhotoIssueType(photo)", app_js)
        self.assertIn("function fieldPhotoIssueAllowed(issueType)", app_js)
        self.assertIn("function fieldPhotoReviewStatus(photo)", app_js)
        self.assertIn("function fieldPhotoGroupKind(photo)", app_js)
        self.assertIn("function pendingFieldPhotoPopup(lat, lon)", app_js)
        self.assertIn("function fieldPhotoPendingReviewPopup(group)", app_js)
        self.assertIn("function rejectFieldPhotoGroup(encodedPhotoIds, button = null)", app_js)
        self.assertIn("fieldPhotoReviewStatus(photo) === 'approved'", app_js)
        self.assertIn("function updateFieldPhotoIssueOptions()", app_js)
        self.assertIn("const enabled = fieldPhotoIssueAllowed(issueType)", app_js)
        self.assertIn("option.disabled = !enabled", app_js)
        self.assertIn("option.hidden = !enabled", app_js)
        self.assertIn("if (!fieldPhotoIssueAllowed(issueType))", app_js)
        self.assertIn("t('modal.fieldPhoto.issueTypeUnavailable')", app_js)
        self.assertIn("function filteredFieldPhotos(photos = fieldPhotoLayerData)", app_js)
        self.assertIn("candidate.issueType === issueType", app_js)
        self.assertIn("function groupFieldPhotos(photos)", app_js)
        self.assertIn("pendingSubmissionIcon('photo')", app_js)
        self.assertIn("fieldPhotoIcon(group.photos.length, group.issueType)", app_js)
        self.assertIn("fieldPhotoGroupPopup(group)", app_js)
        self.assertIn("draggable: adminAuthenticated", app_js)
        self.assertIn("marker.on('dragend', () => updateFieldPhotoGroupLocation(group, marker))", app_js)
        self.assertIn("function updateFieldPhotoLocation(photo, lat, lon)", app_js)
        self.assertIn("function nearestWreckForAttachment(lat, lon)", app_js)
        self.assertIn("function attachFieldPhotoGroupToWreck(group, wreck)", app_js)
        self.assertIn("function createWreckForFieldPhotoGroup(lat, lon, encodedPhotoIds)", app_js)
        self.assertIn("function createManualWreckForFieldPhotoGroup(lat, lon)", app_js)
        self.assertIn("function fieldPhotosForReport(encodedPhotoIds)", app_js)
        self.assertIn("function openFieldPhotoGroupReport(lat, lon, encodedPhotoIds, button = null)", app_js)
        self.assertIn(
            "function openFieldPhotoGroupPhotoUpload(lat, lon, encodedPhotoIds, issueType = FIELD_PHOTO_ISSUE_TYPE_VEHICLE, button = null)",
            app_js,
        )
        self.assertIn("function openPhotoReviewForFieldPhotoGroup(encodedPhotoIds)", app_js)
        self.assertIn("function deleteFieldPhotoGroup(encodedPhotoIds, button = null)", app_js)
        self.assertIn("openFieldPhotoGroupReport(", app_js)
        self.assertIn("openFieldPhotoGroupPhotoUpload(", app_js)
        self.assertIn("openPhotoReviewForFieldPhotoGroup('", app_js)
        self.assertIn("photoReviewExactPhotoIds.join(',')", app_js)
        self.assertIn("deleteFieldPhotoGroup(", app_js)
        self.assertIn("fieldPhotoGroupActions({ ...group, issueType })", app_js)
        self.assertIn(
            "openReportPackageModal(wreckId, { extraPhotos: adminAuthenticated ? [] : fieldPhotosForReport(encodedPhotoIds) })",
            app_js,
        )
        self.assertIn("function appendReportPackageExtraPhotos(formData)", app_js)
        self.assertIn("formData.append('photos[]', blob, photo.filename || 'zdjecie_terenowe.jpg')", app_js)
        self.assertIn("const reportPhotoFiles = publicFeatureAllowed(PUBLIC_FEATURE_KEYS.photoUploads)", app_js)
        self.assertIn("validateReportPackageFiles(reportPhotoFiles, reportPackageExtraPhotos.length)", app_js)
        self.assertIn("if (typeof refreshAdminStatus === 'function') await refreshAdminStatus();", app_js)
        self.assertIn("field-photos/attach", app_js)
        self.assertNotIn("field-photos/link", app_js)
        self.assertIn("FIELD_PHOTO_ATTACH_TO_WRECK_RADIUS_M", app_js)
        self.assertIn("group.issueType === FIELD_PHOTO_ISSUE_TYPE_VEHICLE", app_js)
        self.assertIn("method: 'PATCH'", app_js)
        self.assertIn("await loadFieldPhotos();", app_js)
        self.assertIn("await loadSavedWrecks();", app_js)
        self.assertIn("loadFieldPhotos();", app_js)
        self.assertNotIn("t('fieldPhoto.moveTitle')", app_js)
        self.assertNotIn("t('fieldPhoto.attachToWreckTitle')", app_js)
        self.assertNotIn("async function deleteFieldPhoto(photoId, button = null)", app_js)
        self.assertNotIn("if (!adminAuthenticated) return;\n    groupFieldPhotos(photos)", app_js)
        self.assertNotIn("if (!adminAuthenticated) {\n        clearFieldPhotoMarkers();", app_js)
        self.assertIn("'icon.settings': 'Ustawienia'", i18n_js)
        self.assertIn("'icon.fieldPhotoUpload': 'Dodaj zdjęcia terenowe'", i18n_js)
        self.assertIn("'modal.fieldPhoto.title': 'Zdjęcia terenowe'", i18n_js)
        self.assertIn("'modal.fieldPhoto.issueType': 'Typ miejsca'", i18n_js)
        self.assertIn("'modal.fieldPhoto.chooseFiles': 'Wybierz zdjęcia z terenu'", i18n_js)
        self.assertIn("'modal.fieldPhoto.submit': 'Dodaj na mapę'", i18n_js)
        self.assertIn("'modal.fieldPhoto.submit': 'Add to map'", i18n_js)
        self.assertIn("'fieldPhoto.issueType.infrastructure': 'Niebezpieczna infrastruktura'", i18n_js)
        self.assertIn("'fieldPhoto.issueType.smoke': 'Zanieczyszczone powietrze'", i18n_js)
        self.assertIn("'fieldPhoto.issueType.smoke': 'Polluted air'", i18n_js)
        self.assertIn("'modal.fieldPhoto.issueTypeUnavailable': 'Ta kategoria jest wyłączona w warstwach mapy.'", i18n_js)
        self.assertIn("'modal.fieldPhoto.ignoreExifGps': 'Ignoruj GPS z EXIF i użyj punktu mapy'", i18n_js)
        self.assertNotIn("'fieldPhoto.moveTitle'", i18n_js)
        self.assertNotIn("'fieldPhoto.attachToWreckTitle'", i18n_js)
        self.assertIn("'fieldPhoto.attachToWreckSaving': 'Przenoszę zdjęcia do sprawy pojazdu: {n}...'", i18n_js)
        self.assertIn("'fieldPhoto.attachToWreckSaved': 'Moved photos to vehicle case: {n}.'", i18n_js)
        self.assertIn("'fieldPhoto.reportPackage': 'Generuj zgłoszenie do weryfikacji'", i18n_js)
        self.assertIn("'fieldPhoto.reviewPhotos': 'Edytuj anonimizację zdjęć'", i18n_js)
        self.assertIn("'fieldPhoto.addPhotosHere': 'Dodaj kolejne zdjęcia tutaj'", i18n_js)
        self.assertIn("'fieldPhoto.addPhotosHere': 'Add more photos here'", i18n_js)
        self.assertIn("'fieldPhoto.pendingReview.title': 'Zdjęcie do weryfikacji'", i18n_js)
        self.assertIn("'fieldPhoto.pendingReview.title': 'Photo for review'", i18n_js)
        self.assertIn("'fieldPhoto.rejectError': 'Nie udało się odrzucić zdjęcia terenowego.'", i18n_js)
        self.assertNotIn("fieldPhoto.addPhotosToCase", i18n_js)
        self.assertIn("'fieldPhoto.reviewPhotos': 'Edit photo anonymization'", i18n_js)
        self.assertIn("'fieldPhoto.prepareCaseSaving': 'Przygotowuję sprawę pojazdu...'", i18n_js)
        self.assertIn(
            "'modal.report.extraPublicPhotos': 'Dołączę publiczne zanonimizowane zdjęcia z mapy: {n}.'", i18n_js
        )
        self.assertIn("'modal.report.extraPublicPhotosError': 'Could not attach public map photos.'", i18n_js)
        self.assertIn("'modal.fieldPhoto.fileCountError': 'Choose up to {n} photos at a time.'", i18n_js)
        self.assertIn("'modal.fieldPhoto.retryFailed': 'Retry failed'", i18n_js)
        self.assertIn(
            "'modal.fieldPhoto.uploadSummaryWithErrors': 'Finished: saved {saved}/{total}, errors: {failed}.'", i18n_js
        )
        self.assertIn("'fieldPhoto.source.manual': 'moved manually'", i18n_js)
        self.assertIn("'fieldPhoto.locationUpdated': 'Updated photo position: {n}.'", i18n_js)
        self.assertIn("'fieldPhoto.popup.title': 'Field photo'", i18n_js)
        self.assertIn("'fieldPhoto.popup.groupTitle': 'Field photos: {n}'", i18n_js)
        self.assertIn("width: 300px", styles)
        self.assertIn(".field-photo-toggle", styles)
        self.assertIn(".field-photo-pin", styles)
        self.assertIn(".layer-pin--field-photo-infrastructure", styles)
        self.assertIn(".layer-pin--field-photo-smoke", styles)
        self.assertIn(".field-photo-pin--infrastructure", styles)
        self.assertIn(".field-photo-pin--smoke", styles)
        self.assertIn(".leaflet-marker-draggable .field-photo-pin", styles)
        self.assertIn("field-photo-pin-count", app_js)
        self.assertIn("saved-wreck-pin-count", app_js)
        self.assertIn(".map-pin-count", styles)
        self.assertIn(".field-photo-queue", styles)
        self.assertIn(".field-photo-retry-btn", styles)
        self.assertIn(".file-picker-button", styles)
        self.assertIn(".file-picker-summary", styles)
        self.assertIn(".map-popup-card-grid", styles)
        self.assertIn(".map-popup-thumb", styles)
        self.assertIn(".map-popup-photo-grid", styles)
        self.assertIn(".map-popup-action", styles)
        self.assertIn(".map-popup-text-action", styles)
        self.assertNotIn(".field-photo-popup-grid", styles)
        self.assertNotIn(".wreck-popup-previews", styles)
        self.assertNotIn(".wreck-popup-preview-download", styles)
        self.assertNotIn(".popup-report-btn", styles)

    def test_map_layer_toggles_and_manual_wreck_creation_exist(self):
        html = (ROOT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        app_js = (ROOT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        config_js = (ROOT_DIR / "web" / "config.js").read_text(encoding="utf-8")
        i18n_js = (ROOT_DIR / "web" / "i18n.js").read_text(encoding="utf-8")
        styles = (ROOT_DIR / "web" / "styles.css").read_text(encoding="utf-8")

        self.assertIn('id="map-layer-controls"', html)
        self.assertIn('class="panel-section panel-layers"', html)
        self.assertIn('id="toggle-saved-wrecks"', html)
        self.assertIn('onchange="toggleSavedWreckLayer(this.checked)"', html)
        self.assertIn('id="toggle-cadastral-parcels"', html)
        self.assertIn('onchange="toggleCadastralLayer(this.checked)"', html)
        self.assertIn('id="toggle-surface-layer"', html)
        self.assertIn('onchange="setSurfaceLayerVisible(this.checked)"', html)
        self.assertIn('id="surface-layer-status"', html)
        self.assertIn('id="toggle-field-photo-vehicle"', html)
        self.assertIn('id="toggle-field-photo-infrastructure"', html)
        self.assertIn('id="toggle-field-photo-smoke"', html)
        self.assertIn('id="toggle-field-photo-pending"', html)
        self.assertIn("toggleFieldPhotoIssueFilter('vehicle', this.checked)", html)
        self.assertIn("toggleFieldPhotoIssueFilter('infrastructure', this.checked)", html)
        self.assertIn("toggleFieldPhotoIssueFilter('smoke', this.checked)", html)
        self.assertIn("togglePendingFieldPhotoLayer(this.checked)", html)
        self.assertIn('data-i18n="layers.savedWrecks"', html)
        self.assertIn('data-i18n="layers.cadastral"', html)
        self.assertIn('data-i18n-attr="title:layers.cadastralTooltip"', html)
        self.assertIn('data-i18n="layers.surface"', html)
        self.assertIn('data-i18n="layers.fieldPhotoVehicles"', html)
        self.assertIn('data-i18n="layers.fieldPhotoInfrastructure"', html)
        self.assertIn('data-i18n="layers.fieldPhotoSmoke"', html)
        self.assertIn('data-i18n="layers.fieldPhotoPending"', html)
        self.assertIn("let publicLayerSettingsLoaded = false", app_js)
        self.assertIn("'is-loading-public-layers'", app_js)
        self.assertIn(".map-layer-controls.is-loading-public-layers .layer-toggle", styles)
        self.assertIn("let savedWreckLayerData = []", app_js)
        self.assertIn("let fieldPhotoLayerData = []", app_js)
        self.assertIn("let pendingSubmissionLayer = L.layerGroup().addTo(map)", app_js)
        self.assertIn("function addPendingSubmissionMarker({ lat, lon } = {})", app_js)
        self.assertIn("function clearPendingSubmissionMarkers()", app_js)
        settings_access_slice = app_js[
            app_js.index("function updateSettingsAccess()") : app_js.index("function normalizePublicLayerSettings")
        ]
        self.assertNotIn("clearPendingSubmissionMarkers()", settings_access_slice)
        self.assertIn("let savedWreckLayerVisible = true", app_js)
        self.assertIn("let cadastralLayerVisible = false", app_js)
        self.assertIn("let surfaceLayerVisible = false", app_js)
        self.assertIn("let fieldPhotoIssueFilters = Object.fromEntries", app_js)
        self.assertNotIn("surfaceRasterPane", app_js)
        self.assertIn("const surfacePane = map.createPane('surfacePane')", app_js)
        self.assertIn("surfacePane.style.zIndex = 450", app_js)
        self.assertIn("const CADASTRAL_LAYER_VISIBLE_STORAGE_KEY", config_js)
        self.assertNotIn("SURFACE_LAYER_VISIBLE_STORAGE_KEY", config_js)
        self.assertNotIn("SURFACE_LAYER_VISIBLE_STORAGE_KEY", app_js)
        self.assertNotIn("wroclaw-ortho-surface-visible", config_js + app_js)
        self.assertIn("const SURFACE_FEATURES_URL = '/api/surface/features'", config_js)
        self.assertNotIn("SURFACE_OVERPASS_URL", config_js)
        self.assertIn(
            "const CADASTRAL_WMS_URL = 'https://integracja.gugik.gov.pl/cgi-bin/KrajowaIntegracjaEwidencjiGruntow'",
            config_js,
        )
        self.assertIn("const CADASTRAL_WMS_LAYERS = 'dzialki,numery_dzialek'", config_js)
        self.assertIn("const PUBLIC_LAYER_KEYS = {", config_js)
        self.assertIn("const PUBLIC_FEATURE_KEYS = {", config_js)
        self.assertIn("scanAnalysis: 'scan_analysis'", config_js)
        self.assertIn("yoloWrecks: 'yolo_wrecks'", config_js)
        self.assertIn("manualWrecks: 'manual_wrecks'", config_js)
        self.assertIn("photoUploads: 'photo_uploads'", config_js)
        self.assertIn("baseMapOsm: 'base_map_osm'", config_js)
        self.assertIn("cadastral: 'cadastral'", config_js)
        self.assertIn("surface: 'surface'", config_js)
        self.assertIn("fieldPhotoPending: 'field_photo_pending'", config_js)
        self.assertIn("const FIELD_PHOTO_PUBLIC_LAYER_KEYS = {", config_js)
        self.assertIn("let publicLayerSettings = Object.fromEntries", app_js)
        self.assertIn("function buildCadastralLayer()", app_js)
        self.assertIn("function setCadastralLayerVisible(visible)", app_js)
        self.assertIn("publicLayerAllowed(PUBLIC_LAYER_KEYS.cadastral)", app_js)
        self.assertIn("publicLayerAllowed(PUBLIC_LAYER_KEYS.surface)", app_js)
        self.assertIn("function loadSurfaceLayer()", app_js)
        self.assertIn("function setSurfaceLayerVisible(visible)", app_js)
        self.assertIn("function scheduleSurfaceLayerLoad(delayMs = 650)", app_js)
        self.assertNotIn("function setSurfaceFallbackLayerVisible", app_js)
        self.assertIn("url: OSM_TILE_URL", config_js)
        self.assertIn("maxNativeZoom: 19", config_js)
        self.assertIn("maxNativeZoom: source.maxNativeZoom || MAX_MAP_ZOOM", app_js)
        self.assertIn("function setSurfaceLayerStatus(key = '', params = {}, state = '')", app_js)
        self.assertIn("function surfaceKindLabel(kind)", app_js)
        self.assertIn("function surfaceTagLabel(group, value)", app_js)
        self.assertIn("function surfacePopupRow(labelKey, value)", app_js)
        self.assertIn('class="map-popup map-popup--surface"', app_js)
        self.assertIn("surfacePopupRow('layers.surfacePopup.kind', surfaceKindLabel(props.kind))", app_js)
        self.assertIn("pane: 'surfacePane'", app_js)
        self.assertNotIn("pane: 'surfaceRasterPane'", app_js)
        self.assertIn("function toggleCadastralLayer(visible)", app_js)
        self.assertIn("layers: CADASTRAL_WMS_LAYERS", app_js)
        self.assertIn("styles: 'default,default'", app_js)
        self.assertIn("transparent: true", app_js)
        self.assertIn("localStorage.setItem(CADASTRAL_LAYER_VISIBLE_STORAGE_KEY", app_js)
        self.assertIn("function toggleSavedWreckLayer(visible)", app_js)
        self.assertIn("function toggleFieldPhotoIssueFilter(issueType, visible)", app_js)
        self.assertIn("function togglePendingFieldPhotoLayer(visible)", app_js)
        self.assertIn("function savePublicLayerSettings()", app_js)
        self.assertIn("function publicLayerAllowed(layerKey)", app_js)
        self.assertIn("let publicFeatureSettings = Object.fromEntries", app_js)
        self.assertIn("function savePublicFeatureSettings()", app_js)
        self.assertIn("function publicFeatureAllowed(featureKey)", app_js)
        self.assertIn("runButton.hidden = !scanAllowed", app_js)
        self.assertIn("const yoloWrecksAllowed = publicFeatureAllowed(PUBLIC_FEATURE_KEYS.yoloWrecks)", app_js)
        self.assertIn("data-yolo-wreck-save", app_js)
        self.assertIn("if (!publicFeatureAllowed(PUBLIC_FEATURE_KEYS.yoloWrecks))", app_js)
        self.assertIn("contextCrosshairButton.hidden = !scanAllowed", app_js)
        self.assertIn("contextFieldPhotoButton.hidden = !photoUploadsAllowed", app_js)
        self.assertIn("const manualWrecksAllowed = publicFeatureAllowed(PUBLIC_FEATURE_KEYS.manualWrecks)", app_js)
        self.assertIn("const canAddFieldPhotosHere = coordinatesOk", app_js)
        self.assertIn("&& publicFeatureAllowed(PUBLIC_FEATURE_KEYS.photoUploads)", app_js)
        self.assertIn("&& fieldPhotoIssueAllowed(issueType)", app_js)
        self.assertIn("const photoButton = canAddFieldPhotosHere", app_js)
        self.assertIn("if (!publicFeatureAllowed(PUBLIC_FEATURE_KEYS.manualWrecks)) return null;", app_js)
        self.assertIn("if (!publicFeatureAllowed(PUBLIC_FEATURE_KEYS.manualWrecks)) return;", app_js)
        self.assertIn("await openFieldPhotoUploadModal({", app_js)
        self.assertIn("fieldPhotoIssueFilters[safeIssueType] = Boolean(visible)", app_js)
        self.assertIn("let pendingFieldPhotoLayerVisible = true", app_js)
        self.assertIn("publicLayerAllowed(PUBLIC_LAYER_KEYS.fieldPhotoPending)", app_js)
        self.assertIn("groupFieldPhotos(filteredFieldPhotos(photos)).forEach", app_js)
        self.assertIn("function countLingeringCars()", app_js)
        self.assertIn("function updateLingeringCarsCounter()", app_js)
        self.assertIn("Number(wreck.photo_count) > 0", app_js)
        self.assertIn("const vehiclePhotos = publicLayerAllowed(PUBLIC_LAYER_KEYS.fieldPhotoVehicle)", app_js)
        self.assertIn("groupFieldPhotos(vehiclePhotos).length", app_js)
        self.assertIn("document.addEventListener('langchange', updateLingeringCarsCounter)", app_js)
        self.assertIn(
            "if (!savedWreckLayerVisible || !publicLayerAllowed(PUBLIC_LAYER_KEYS.savedWrecks)) return;", app_js
        )
        self.assertNotIn("fieldPhotoLayerVisible", app_js)
        self.assertNotIn("toggleFieldPhotoLayer", app_js)
        self.assertIn("savedWreckLayerData = data.wrecks || []", app_js)
        self.assertIn("fieldPhotoLayerData = data.photos || []", app_js)
        self.assertIn("function saveManualWreck(lat, lon, button = null)", app_js)
        self.assertIn("function selectedReviewCropM()", app_js)
        self.assertIn("addPendingSubmissionMarker({ lat: data.wreck?.lat", app_js)
        self.assertIn("addPendingSubmissionMarker({ lat: data.wreck?.lat ?? latNumber", app_js)
        self.assertIn("t('inspect.submittedWreck')", app_js)
        self.assertIn("body: JSON.stringify({ lat: latNumber, lon: lonNumber, cropM })", app_js)
        self.assertIn("body: JSON.stringify({ lat: inspectLat, lon: inspectLon, cropM: selectedReviewCropM() })", app_js)
        self.assertIn("saveManualWreck(${inspectLat.toFixed(8)}, ${inspectLon.toFixed(8)}, this)", app_js)
        self.assertIn("'layers.savedWrecks': 'Sprawy pojazdów'", i18n_js)
        self.assertIn("'layers.cadastral': 'Granice działek'", i18n_js)
        self.assertIn(
            "'layers.cadastralTooltip': 'Działki ewidencyjne KIEG/GUGiK: granice i numery działek, bez danych właścicieli.'",
            i18n_js,
        )
        self.assertIn("'layers.surface': 'Nawierzchnia'", i18n_js)
        self.assertIn("'layers.surfaceLoading': 'ładuję...'", i18n_js)
        self.assertNotIn("'layers.surfaceRasterFallback'", i18n_js)
        self.assertIn("'layers.baseMapOsm': 'Mapa OSM'", i18n_js)
        self.assertIn("'layers.surfacePopup.kind': 'Rodzaj'", i18n_js)
        self.assertIn("'layers.surfaceKind.sidewalk': 'chodnik / ciąg pieszy'", i18n_js)
        self.assertIn("'layers.surfaceHighway.service': 'droga wewnętrzna / dojazdowa'", i18n_js)
        self.assertIn("'layers.surfaceMaterial.paving_stones': 'kostka brukowa'", i18n_js)
        self.assertIn("'layers.surfaceKerb.lowered': 'obniżony'", i18n_js)
        self.assertIn("'layers.surfacePopup.kind': 'Type'", i18n_js)
        self.assertIn("'layers.fieldPhotoVehicles': 'Zdjęcia pojazdów'", i18n_js)
        self.assertIn("'layers.fieldPhotoInfrastructure': 'Niebezpieczna infrastruktura'", i18n_js)
        self.assertIn("'layers.fieldPhotoSmoke': 'Zanieczyszczone powietrze'", i18n_js)
        self.assertIn("'layers.fieldPhotoPending': 'Do weryfikacji'", i18n_js)
        self.assertIn("'pendingSubmission.reviewHint': 'Czeka na zatwierdzenie administratora. Ten znacznik jest widoczny tylko lokalnie.'", i18n_js)
        self.assertIn("'fieldPhoto.pendingPublicHint': 'Czeka na zatwierdzenie administratora.'", i18n_js)
        self.assertIn("'modal.fieldPhoto.submittedForReview': 'Zdjęcia wysłane do weryfikacji: {n}.'", i18n_js)
        self.assertIn("'wreck.submittedForReview': 'Zgłoszenie zapisane i czeka na zatwierdzenie administratora.'", i18n_js)
        self.assertIn(".pending-submission-pin", styles)
        self.assertNotIn(".map-popup-thumb--pending", styles)
        self.assertIn("'layers.fieldPhotoSmoke': 'Polluted air'", i18n_js)
        self.assertIn("'layers.fieldPhotoVehicles': 'Vehicle photos'", i18n_js)
        self.assertIn("'layers.fieldPhotoPending': 'For review'", i18n_js)
        self.assertIn("'layers.cadastral': 'Parcel boundaries'", i18n_js)
        self.assertIn("'layers.baseMapOsm': 'OSM map'", i18n_js)
        self.assertIn("'layers.title': 'Warstwy'", i18n_js)
        self.assertIn("'inspect.saveWreck': 'Dodaj z wycinkiem'", i18n_js)
        self.assertIn("'inspect.saveWreck': 'Add with crop'", i18n_js)
        self.assertIn(".map-layer-controls", styles)
        self.assertNotIn("right: 16px;\n    bottom: 96px", styles)
        self.assertIn(".layer-toggle input:checked::after", styles)
        self.assertIn(".layer-pin--wreck", styles)
        self.assertIn(".layer-pin--cadastral", styles)
        self.assertIn(".layer-pin--surface", styles)
        self.assertIn(".layer-pin--base-map-osm", styles)
        self.assertIn(".layer-status.is-error", styles)
        self.assertIn(".map-popup--surface", styles)
        self.assertIn(".surface-popup-row", styles)
        self.assertIn(".layer-pin--field-photo-vehicle", styles)
        self.assertIn(".layer-pin--field-photo-infrastructure", styles)
        self.assertIn(".layer-pin--field-photo-smoke", styles)

    def test_scan_area_controls_context_menu_and_crosshair_contract(self):
        html = (ROOT_DIR / "web" / "index.html").read_text(encoding="utf-8")
        app_js = (ROOT_DIR / "web" / "app.js").read_text(encoding="utf-8")
        config_js = (ROOT_DIR / "web" / "config.js").read_text(encoding="utf-8")
        i18n_js = (ROOT_DIR / "web" / "i18n.js").read_text(encoding="utf-8")
        styles = (ROOT_DIR / "web" / "styles.css").read_text(encoding="utf-8")
        todo_md = (ROOT_DIR / "docs" / "todo.md").read_text(encoding="utf-8")

        self.assertIn('data-i18n="modal.settings.scanArea"', html)
        self.assertIn('id="width-slider" min="50" max="50"', html)
        self.assertIn("const SCAN_AREA_MIN_M = 50", config_js)
        self.assertIn("const SCAN_AREA_MAX_M = 50", config_js)
        self.assertIn("const CROSSHAIR_MAX_VIEWPORT_RATIO = 0.82", config_js)
        self.assertIn("const CROSSHAIR_HIDDEN_STORAGE_KEY = 'wroclaw-ortho-crosshair-hidden'", config_js)
        self.assertIn("const FIELD_PHOTO_ATTACH_TO_WRECK_RADIUS_M = 1", config_js)
        self.assertIn("const MARKER_DETAIL_FULL_MIN_ZOOM = 18", config_js)
        self.assertIn("const MARKER_DETAIL_DOT_MAX_ZOOM = 16", config_js)
        self.assertIn("function clampScanSize(value)", app_js)
        self.assertIn("widthSlider.hidden = SCAN_AREA_MIN_M === SCAN_AREA_MAX_M", app_js)
        self.assertIn("const snap = clampScanSize", app_js)
        self.assertIn("function updateMarkerDetailMode()", app_js)
        self.assertIn("map.on('zoomend', updateMarkerDetailMode)", app_js)
        self.assertIn("map.on('popupopen'", app_js)
        self.assertIn("crosshair?.classList.toggle(", app_js)
        self.assertIn("'is-hidden',", app_js)
        self.assertIn(
            "let crosshairManuallyHidden = localStorage.getItem(CROSSHAIR_HIDDEN_STORAGE_KEY) === '1'", app_js
        )
        self.assertIn("function toggleCrosshairFromContextMenu()", app_js)
        self.assertIn("if (!publicFeatureAllowed(PUBLIC_FEATURE_KEYS.scanAnalysis)) return;", app_js)
        self.assertIn("function setCrosshairManuallyHidden(hidden)", app_js)
        self.assertIn("localStorage.setItem(CROSSHAIR_HIDDEN_STORAGE_KEY", app_js)
        self.assertIn("function updateContextCrosshairLabel()", app_js)
        self.assertIn("document.addEventListener('langchange', updateContextCrosshairLabel)", app_js)
        self.assertIn('id="map-context-menu"', html)
        self.assertIn('id="context-toggle-crosshair"', html)
        self.assertIn('id="context-crosshair-label"', html)
        self.assertIn('onclick="toggleCrosshairFromContextMenu()"', html)
        self.assertIn("map.on('contextmenu'", app_js)
        self.assertIn("function centerScanOnContextPoint()", app_js)
        self.assertIn("function openFieldPhotoUploadAtContextPoint()", app_js)
        self.assertIn("openFieldPhotoUploadModal({", app_js)
        self.assertIn("ignoreExifGps: true", app_js)
        self.assertIn("function identifyCadastralParcelAtContextPoint()", app_js)
        self.assertIn("function cadastralParcelPopup(parcel = {})", app_js)
        self.assertIn("function cadastralCodeLabel(code)", app_js)
        self.assertIn("function cadastralParcelGeoportalUrl(parcel = {})", app_js)
        self.assertIn("function copyActiveCadastralParcel()", app_js)
        self.assertIn("const CADASTRAL_LAND_USE_LABEL_KEYS", app_js)
        self.assertIn("parcel.land_use || parcel.contour", app_js)
        self.assertIn("const contourLabel = cadastralCodeLabel(parcel.contour)", app_js)
        self.assertIn("contourLabel !== terrainType && contourLabel !== landUse", app_js)
        self.assertIn("fetch(url, { cache: 'no-store' })", app_js)
        self.assertIn("const CADASTRAL_IDENTIFY_URL = '/api/cadastral/identify'", config_js)
        self.assertIn("let fieldPhotoUploadFallbackLatLng = null", app_js)
        self.assertIn("function currentFieldPhotoUploadFallbackLatLng()", app_js)
        self.assertIn("function copyContextCoords()", app_js)
        self.assertIn("function copyContextPlaceLink()", app_js)
        self.assertIn("appPlaceUrl(contextMenuLatLng.lat, contextMenuLatLng.lng, map.getZoom())", app_js)
        self.assertIn("'context.centerScan': 'Ustaw środek skanu'", i18n_js)
        self.assertIn("'context.addFieldPhotos': 'Dodaj zdjęcia tutaj'", i18n_js)
        self.assertIn("'context.identifyParcel': 'Sprawdź działkę'", i18n_js)
        self.assertIn("'context.parcelTerrainType': 'Typ terenu'", i18n_js)
        self.assertIn("'context.parcelLandUse': 'Użytek'", i18n_js)
        self.assertIn("'context.parcelContour': 'Kontur'", i18n_js)
        self.assertIn("'context.parcelCopyData': 'Kopiuj dane działki'", i18n_js)
        self.assertIn("'context.landUse.dr': 'droga / pas drogowy'", i18n_js)
        self.assertNotIn("context.parcelOwnerHint", i18n_js)
        self.assertNotIn("context.parcelSurfaceHint", i18n_js)
        self.assertNotIn("context.parcelRegistryGroupMissing", i18n_js)
        self.assertNotIn("parcel.registry_group || t('context.parcelRegistryGroupMissing')", app_js)
        self.assertIn("'context.hideCrosshair': 'Ukryj celownik'", i18n_js)
        self.assertIn("'context.showCrosshair': 'Pokaż celownik'", i18n_js)
        self.assertIn("'context.copyPlaceLink': 'Skopiuj link do miejsca'", i18n_js)
        self.assertIn("'context.copiedPlaceLink': 'Skopiowano link do miejsca.'", i18n_js)
        self.assertIn('data-i18n="context.addFieldPhotos"', html)
        self.assertIn('data-i18n="context.identifyParcel"', html)
        self.assertIn('data-i18n="context.hideCrosshair"', html)
        self.assertIn('data-i18n="context.copyPlaceLink"', html)
        self.assertIn("'modal.help.dataSource': 'Data: Wrocław WMS + Polish Geoportal WFS/GeoTIFF cache.'", i18n_js)
        self.assertIn("#crosshair.is-hidden", styles)
        self.assertIn(".map-context-menu", styles)
        self.assertIn(".marker-detail--compact .map-pin-count", styles)
        self.assertIn(".marker-detail--dots .saved-wreck-pin", styles)
        self.assertIn(".marker-detail--dots .field-photo-pin", styles)
        self.assertIn(".parcel-popup-row", styles)
        self.assertIn("Doprecyzowanie oficjalnych źródeł nawierzchni", todo_md)
        self.assertIn("Warstwa nawierzchni OSM/Overpass", todo_md)
        self.assertIn("OSM/Overpass", todo_md)
        self.assertIn("BDOT10k/SIP Wrocławia", todo_md)


if __name__ == "__main__":
    unittest.main()
